services:
  db:
    image: postgres:latest
    container_name: tech-challenge-restaurante
    environment:
      POSTGRES_DB: tech-challenge-restaurantes
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 102030
    expose:
      - 5432
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always
  springboot-app:
    container_name: springboot_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db  

volumes:
  pg_data:
  springboot-app: